/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"

#ifndef _Included_com_xah_send_logic_jni_WindowsJni
#define _Included_com_xah_send_logic_jni_WindowsJni
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_com_xah_send_logic_jni_WindowsJni_pickSingleFile
  (JNIEnv * env, jobject obj);

JNIEXPORT jboolean JNICALL Java_com_xah_send_logic_jni_WindowsJni_warn
  (JNIEnv * env, jobject obj, jstring windowName);

JNIEXPORT jstring JNICALL Java_com_xah_send_logic_jni_WindowsJni_getDownloadFolder
        (JNIEnv * env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
